---
- name: Install apache2
  hosts: test
  gather_facts: false
  become: yes

  tasks:

   - name: apache2 install
     apt:
       name: apache2
       state: present
     notify: installation_apache

   - name: apache2 start
     systemd:
       name: apache2
       state: reloaded
     notify: service_start_apache

  handlers:

   - name: installation_apache
     slack:
      domain: hooks.slack.com
      token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      msg: "{{ inventory_hostname }} action completed"
      channel: "#demo-tower"
   - name: service_start_apache
     slack:
      domain: hooks.slack.com
      token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      msg: "{{ inventory_hostname }} start apache2 service"
      channel: "#demo-tower"
