---
- name: Create user "{{ user }}"
  hosts: test
  gather_facts: true

  tasks:

    - name: Add the user ""{{ user }}" with uid and primary group
      user:
        name: "{{ user }}"
        comment: User created by Ansible Tower
        uid: 1040
        group: "{{ group }}"
      register: out_lines
    - debug: var=out_lines
