---
- name: Haproxy Config Backend
  hosts: frontendlb
  become: yes

  vars:
    server: web01
    privateip: 172.100.0.6
    backend: app_webserver01

  tasks:

    - name: set new parameters
      template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
      register: out_lines
    - debug: var=out_lines
      notify:
         - restart apache2

  handlers:
    - name: restart Haproxy
      systemd:
        state: restarted
        name: haproxy
