---
- name: Package for Apache2
  hosts: web01
  gather_facts: true
  tasks:

    - name: Install apache2
      apt:
        name: apache2
        update_cache: yes
      register: out_lines
    - debug: var=out_lines
