---
- name: Create user "{{ inventory_hostname }}"
  hosts: webservers
  gather_facts: true

  tasks:

    - name: Disable server, provide socket file, wait until status reports in maintenance
      haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
        socket: /var/run/haproxy/admin.sock
        backend: app_webserver01
      register: out_lines
    - debug: var=out_lines
