---
- name: Add ppa for Haproxy
  hosts: lb02
  gather_facts: true
  tasks:
    - name: PPA Haproxy 1.8
      apt_repository:
        repo: 'ppa:vbernat/haproxy-1.8'
      register: result

    - name: Display Haproxy PPA
      debug:
        msg: result

    - name: Update Cache and  install Haproxy 1.8
      apt:
        name: haproxy
        update_cache: yes
