---
- name: Install apache2
  hosts: webservers
  gather_facts: false
  become: yes

  tasks:

   - name: apache2 install
     apt:
       name: apache2
       state: present
     notify: installation_apache

   - name: apache2 start
     systemd:
       name: apache2
       state: started
     notify: service_start_apache

  handlers:

   - name: installation_apache
     slack:
      domain: hooks.slack.com
      token: "TMSBL3AR1/BQPA5PKNG/B9oVZCxZtlTsermrh7dz046F"
      msg: "action completed"
      channel: "#demo-tower"
   - name: service_start_apache
     slack:
      domain: hooks.slack.com
      token: "TMSBL3AR1/BQPA5PKNG/B9oVZCxZtlTsermrh7dz046F"
      msg: "start apache2 service"
      channel: "#demo-tower"
