---
- name: Remove user "{{ user }}"
  hosts: all
  gather_facts: true

  tasks:

    - name: Remove on all webservers "{{ user }}"
      user:
        name: "{{ user }}"
        state: absent
        remove: yes
      register: out_lines
    - debug: var=out_lines
