- name: remove apache2
  hosts: web03
  gather_facts: true
  tasks:

    - name: remove apache2
      apt:
        name: apache2
        state: absent
        force_apt_get: yes
        update_cache: yes
      register: result
    - debug: var=result
