---
- name: Add user on all hosts
  hosts: all
  become: yes

  tasks:
    - name: Remove {{ user }}
      user:
        name: {{ user }}
        state: absent
        remove: yes
      register: out_lines
    - debug: var=out_lines
