- name: remove apache2
  hosts: web03
  gather_facts: true
  tasks:

    - name: remove apache2
      apt:
        name: apache2
        force_apt_get: yes
        state: absent
      register: result
    - debug: var=result

    - name: Remove useless packages from the cache
      apt:
       autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
