---
- name: Running Services on Server Windows
  hosts: WinServers
  tasks:

    - name: get service 
      win_shell: Get-Service | Where-Object Status -EQ "Running" | Select "Status","Name","DisplayName"
      register: Status_out
    - debug: var=Status_out
