---
- name: Only search and list what found
  hosts: WS12R201-ST

  tasks:
    - name: Searching Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - Updates
          - UpdateRollups
        log_path: c:\ansible_wu.txt
        state: searched
      register: Status_out
    - debug: var=Status_out
