---
- name: site webserver
  hosts: web01
  become: yes

  tasks:

    - name: Check content of web and status
      uri:
        url: https://app.b2cloud.com.ar
        return_content: yes
      register: out_lines
      failed_when: "{{ wordtofind }}"
